apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: waleedakramkhann/hotelserver
          ports:
            - containerPort: 3001
          env:
            - name: SQLUSER
              value: root
            - name: SQLHOST
              value: mysql-cluster-ip-service
            - name: SQLPORT
              value: "3306"
            - name: SQLDATABASE
              value: hoteldb
            - name: SQLPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: MYSQLPASSWORD
